steps:
  # Create hugo content directory
  - name: busybox
    id: mk-contentdir
    args:
      - mkdir
      - '-p'
      - site/content/minutes

  # Retrieve generated docs from bucket
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: sync-content
    entrypoint: gsutil
    args:
      - '-m'
      - rsync
      - '-r'
      - gs://$_CONTENT_BUCKET/minutes/
      - site/content/minutes/

  # Build the static site with hugo
  - name: hugomods/hugo:debian-std-node-lts-0.161.1
    id: hugo-build
    args:
      - '--source=site'
      - '--minify'
    waitFor:
      - sync-content

  # Install firebase-tools
  - name: node
    id: install-firebase
    entrypoint: npm
    args:
      - install
      - firebase-tools
    waitFor:
      - hugo-build

  # Deploy the firebase hosting site
  - name: node
    id: firebase-deploy
    entrypoint: ./node_modules/.bin/firebase
    args:
      - deploy
      - '--only'
      - hosting
      - '--project'
      - $_FIREBASE_PROJECT
      - '--non-interactive'
    waitFor:
      - install-firebase

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _FIREBASE_PROJECT: miltonmeetingsummarizer
  _CONTENT_BUCKET: ${PROJECT_ID}-hugo-content
