steps:
  # Create hugo content directory
  - name: busybox
    id: mk-contentdir
    args:
      - mkdir
      - '-p'
      - site/content/minutes


  # Retrieve generated docs from bucket
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: sync-content
    args:
      - '-m'
      - rsync
      - '-r'
      - gs://$_CONTENT_BUCKET/minutes/
      - site/content/minutes/
    entrypoint: gsutil

  # Build the static site with hugo
  - name: hugomods/hugo:debian-std-node-lts-0.161.1
    id: hugo-build
    args:
      - '--source=site'
      - '--minify'
    waitFor:
      - sync-content

  # Install firebase-tools
  - name: node
    id: install-firebase
    args:
      - install
      - firebase-tools
    waitFor:
      - hugo-build
    entrypoint: npm

  # Deploy the firebase hosting site
  - name: node
    id: firebase-deploy
    args:
      - deploy
      - '--only'
      - hosting
      - '--project'
      - $_FIREBASE_PROJECT
      - '--token'
      - $$FIREBASE_TOKEN
      - '--non-interactive'
    waitFor:
      - install-firebase
    entrypoint: ./node_modules/.bin/firebase
    secretEnv:
      - FIREBASE_TOKEN

substitutions:
  _CONTENT_BUCKET: ${PROJECT_ID}-hugo-content
  _FIREBASE_PROJECT: miltonmeetingsummarizer

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/firebase-ci-token/versions/latest
      env: FIREBASE_TOKEN

options:
  logging: CLOUD_LOGGING_ONLY
